### ISSUE TITLE
Contributors Image is broken on the About Page

### ISSUE THREAD

**Issue by realrohitgurav** [mirazxmondal/Sharadiya#11]
The contributors images are appearing as broken in the about.html file highlighted in blue in below screenshot. 

![broken](https://user-images.githubusercontent.com/110970889/237038565-10c35058-45d5-443a-a149-534675e63b02.jpg)

**Comment by mirazxmondal** [comment]
Yes we are aware of this issue and thank you for raising an issue, however this contributors section will be removed and GitHub contributors names will be displayed dynamically in the upcoming future
